In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
df=pd.read_csv('Social_Network_Ads.csv')


In [10]:
X=df.iloc[:, 1:-1].values
y=df.iloc[:, -1].values

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y,test_size=0.25, random_state=0)

In [12]:
print(X_train)

[[ 39000]
 [120000]
 [ 50000]
 [135000]
 [ 21000]
 [104000]
 [ 42000]
 [ 61000]
 [ 50000]
 [ 63000]
 [ 25000]
 [ 50000]
 [ 73000]
 [ 49000]
 [ 29000]
 [ 65000]
 [131000]
 [ 89000]
 [ 82000]
 [ 51000]
 [ 15000]
 [102000]
 [112000]
 [107000]
 [ 53000]
 [ 59000]
 [ 41000]
 [134000]
 [113000]
 [148000]
 [ 15000]
 [ 42000]
 [ 19000]
 [149000]
 [ 96000]
 [ 59000]
 [ 96000]
 [ 89000]
 [ 72000]
 [ 26000]
 [ 69000]
 [ 82000]
 [ 74000]
 [ 80000]
 [ 72000]
 [149000]
 [ 71000]
 [146000]
 [ 79000]
 [ 75000]
 [ 51000]
 [ 75000]
 [ 78000]
 [ 61000]
 [108000]
 [ 82000]
 [ 74000]
 [ 65000]
 [ 80000]
 [117000]
 [ 61000]
 [ 68000]
 [ 44000]
 [ 87000]
 [ 33000]
 [ 90000]
 [ 42000]
 [123000]
 [118000]
 [ 87000]
 [ 71000]
 [ 70000]
 [ 39000]
 [ 23000]
 [147000]
 [138000]
 [ 86000]
 [ 79000]
 [138000]
 [ 23000]
 [ 60000]
 [113000]
 [107000]
 [ 33000]
 [ 80000]
 [ 96000]
 [ 18000]
 [ 71000]
 [129000]
 [ 76000]
 [ 44000]
 [118000]
 [ 90000]
 [ 30000]
 [ 43000]
 [ 78000]
 [ 59000]
 [ 42000]
 [ 74000]
 [ 91000]


In [13]:
print(y_train)

[0 1 0 1 1 1 0 0 0 0 0 0 1 1 1 0 1 0 0 1 0 1 0 1 0 0 1 1 1 1 0 1 0 1 0 0 1
 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 0 1 0 0 0 1 0 0 0 1 1 0 0 1 0 1
 1 1 0 0 1 1 0 0 1 1 0 1 0 0 1 1 0 1 1 1 0 0 0 0 0 1 0 0 1 1 1 1 1 0 1 1 0
 1 0 0 0 0 0 0 0 1 1 0 0 1 0 0 1 0 0 0 1 0 1 1 0 1 0 0 0 0 1 0 0 0 1 1 0 0
 0 0 1 0 1 0 0 0 1 0 0 0 0 1 1 1 0 0 0 0 0 0 1 1 1 1 1 0 1 0 0 0 0 0 1 0 0
 0 0 0 0 1 1 0 1 0 1 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 0 0 0 0
 0 1 1 0 0 0 0 1 0 0 0 0 1 0 1 0 1 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 1 1 0 0 0
 0 0 1 0 1 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 1 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1
 0 0 0 0]


In [14]:
print(X_test)

[[ 87000]
 [ 50000]
 [ 75000]
 [ 79000]
 [ 50000]
 [ 20000]
 [ 15000]
 [144000]
 [ 68000]
 [ 43000]
 [ 49000]
 [ 55000]
 [ 55000]
 [ 77000]
 [ 86000]
 [117000]
 [ 77000]
 [ 85000]
 [130000]
 [ 22000]
 [ 47000]
 [144000]
 [ 51000]
 [105000]
 [ 28000]
 [141000]
 [ 87000]
 [ 80000]
 [ 62000]
 [ 86000]
 [ 88000]
 [ 79000]
 [ 60000]
 [ 53000]
 [ 58000]
 [ 52000]
 [ 81000]
 [ 43000]
 [ 34000]
 [ 36000]
 [ 88000]
 [ 52000]
 [ 84000]
 [ 20000]
 [112000]
 [ 58000]
 [ 80000]
 [ 90000]
 [ 30000]
 [ 86000]
 [122000]
 [ 25000]
 [ 57000]
 [115000]
 [ 88000]
 [ 32000]
 [ 83000]
 [ 80000]
 [ 28000]
 [ 20000]
 [ 18000]
 [ 42000]
 [ 76000]
 [ 99000]
 [ 26000]
 [ 83000]
 [ 89000]
 [ 58000]
 [ 47000]
 [ 70000]
 [150000]
 [ 77000]
 [ 63000]
 [ 22000]
 [ 89000]
 [ 82000]
 [ 79000]
 [ 60000]
 [ 34000]
 [107000]
 [144000]
 [ 83000]
 [ 55000]
 [ 35000]
 [ 38000]
 [ 80000]
 [ 75000]
 [130000]
 [ 41000]
 [ 60000]
 [ 64000]
 [146000]
 [ 48000]
 [ 33000]
 [ 84000]
 [ 96000]
 [ 63000]
 [ 33000]
 [ 90000]
 [104000]]

In [15]:
print(y_test)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 0 0 0 1 0 1 1 1]


In [16]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)


In [17]:
print(X_train)

[[-0.88670699]
 [ 1.46173768]
 [-0.5677824 ]
 [ 1.89663484]
 [-1.40858358]
 [ 0.99784738]
 [-0.79972756]
 [-0.24885782]
 [-0.5677824 ]
 [-0.19087153]
 [-1.29261101]
 [-0.5677824 ]
 [ 0.09905991]
 [-0.59677555]
 [-1.17663843]
 [-0.13288524]
 [ 1.78066227]
 [ 0.56295021]
 [ 0.35999821]
 [-0.53878926]
 [-1.58254245]
 [ 0.93986109]
 [ 1.22979253]
 [ 1.08482681]
 [-0.48080297]
 [-0.30684411]
 [-0.8287207 ]
 [ 1.8676417 ]
 [ 1.25878567]
 [ 2.27354572]
 [-1.58254245]
 [-0.79972756]
 [-1.46656987]
 [ 2.30253886]
 [ 0.76590222]
 [-0.30684411]
 [ 0.76590222]
 [ 0.56295021]
 [ 0.07006676]
 [-1.26361786]
 [-0.01691267]
 [ 0.35999821]
 [ 0.12805305]
 [ 0.30201192]
 [ 0.07006676]
 [ 2.30253886]
 [ 0.04107362]
 [ 2.21555943]
 [ 0.27301877]
 [ 0.1570462 ]
 [-0.53878926]
 [ 0.1570462 ]
 [ 0.24402563]
 [-0.24885782]
 [ 1.11381995]
 [ 0.35999821]
 [ 0.12805305]
 [-0.13288524]
 [ 0.30201192]
 [ 1.37475825]
 [-0.24885782]
 [-0.04590581]
 [-0.74174127]
 [ 0.50496393]
 [-1.06066585]
 [ 0.59194336]
 [-0.79972

In [18]:
print(X_test)

[[ 0.50496393]
 [-0.5677824 ]
 [ 0.1570462 ]
 [ 0.27301877]
 [-0.5677824 ]
 [-1.43757673]
 [-1.58254245]
 [ 2.15757314]
 [-0.04590581]
 [-0.77073441]
 [-0.59677555]
 [-0.42281668]
 [-0.42281668]
 [ 0.21503249]
 [ 0.47597078]
 [ 1.37475825]
 [ 0.21503249]
 [ 0.44697764]
 [ 1.75166912]
 [-1.37959044]
 [-0.65476184]
 [ 2.15757314]
 [-0.53878926]
 [ 1.02684052]
 [-1.20563157]
 [ 2.07059371]
 [ 0.50496393]
 [ 0.30201192]
 [-0.21986468]
 [ 0.47597078]
 [ 0.53395707]
 [ 0.27301877]
 [-0.27785096]
 [-0.48080297]
 [-0.33583725]
 [-0.50979612]
 [ 0.33100506]
 [-0.77073441]
 [-1.03167271]
 [-0.97368642]
 [ 0.53395707]
 [-0.50979612]
 [ 0.41798449]
 [-1.43757673]
 [ 1.22979253]
 [-0.33583725]
 [ 0.30201192]
 [ 0.59194336]
 [-1.14764529]
 [ 0.47597078]
 [ 1.51972397]
 [-1.29261101]
 [-0.3648304 ]
 [ 1.31677196]
 [ 0.53395707]
 [-1.089659  ]
 [ 0.38899135]
 [ 0.30201192]
 [-1.20563157]
 [-1.43757673]
 [-1.49556302]
 [-0.79972756]
 [ 0.18603934]
 [ 0.85288166]
 [-1.26361786]
 [ 0.38899135]
 [ 0.56295

In [19]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()
classifier.fit(X_train, y_train)

LogisticRegression()

In [21]:
pred=classifier.predict(X_test)
print(np.concatenate((pred.reshape(len(pred),1),y_test.reshape(len(pred),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 1]
 [1 1]]


In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test, pred)
print(cm)
accuracy_score(y_test, pred)

[[66  2]
 [17 15]]


0.81